window.WEDDING_TEXT = {
  coupleNames: "Khắc Tín - Yến Nhi",
  monogram: "T&N",
  weddingDate: "03.05.2026",
  // Dung cho countdown (ISO). Vi du: "2026-05-03T17:00:00+07:00"
  countdownTarget: "2026-05-03T17:00:00+11:00",
  inviteMessage: "Trân trọng kính mời quý khách tới dự bữa tiệc mừng lễ thành hôn của hai chúng tôi",
  coupleScript: "Khắc Tín<br>Yến Nhi",
  /** Hôn lễ tại nhà thờ — sửa nội dung tại đây */
  ceremonyChurchTitle: "Hôn lễ được cử hành tại Thánh đường Giáo xứ Vinh Trung",
  ceremonyChurchTime: "Vào lúc 10 giờ 00",
  ceremonyChurchDate: "Thứ Bảy · 02.05.2026",
  ceremonyChurchLunar: "(Nhằm ngày 16 tháng 03 năm Bính Ngọ)",
  /** Lễ thành hôn tại tư gia */
  ceremonyHomeTitle: "Lễ thành hôn được cử hành tại tư gia",
  ceremonyHomeTime: "Vào lúc 09 giờ 00",
  ceremonyHomeDate: "Thứ Bảy · 09.05.2026",
  ceremonyHomeLunar: "(Nhằm ngày 23 tháng 03 năm Bính Ngọ)",
  eventTime: "VÀO LÚC 11 GIỜ | CHỦ NHẬT",
  eventDateText: "NGÀY 03 THÁNG 05 NĂM 2026",
  eventDateLunar: "(TỨC NGÀY 17 THÁNG 03 NĂM BÍNH NGỌ)",
  brideFamily: "Ông Giuse Trần Ngọc Triệu<br>Bà Maria Phạm Thị Bích Luận",
  groomFamily: "Ông Phêrô Hồ Ngọc Cẩn<br>Bà Lucia Trần Thị Ngọc Linh",
  venueName: "Nhà Hàng Bá Hùng",
  venueAddress: "126A NGUYỄN TẤT THÀNH, P. BÀ RỊA, TP. Hồ Chí Minh",
  mapLink: "https://maps.app.goo.gl/yDk8pDZEdzDnJLib8",
  timelineDate: "03 . 05 . 2026",
  giftTitle: "Hộp mừng cưới",
  giftSubtitle: "Cảm ơn tình cảm của mọi người đã dành cho chúng mình!",
  guestbookTitle: "Sổ lưu bút",
  guestbookThankYouMessage:
    "Cảm ơn lời chúc tốt đẹp từ bạn đến cô dâu và chú rể.",
  rsvpThankYouMessage:
    "Sự hiện diện của bạn sẽ là niềm vinh hạnh cho gia đình chúng tôi.",
  footerTitle: "Thank you",
  footerMessage: "Cảm ơn bạn đã dành tình cảm cho chúng mình!<br>Sự hiện diện của bạn chính là món quà ý nghĩa nhất.",
  albumCaption1: "Khoảnh khắc đầu tiên khi mình nhìn về nhau.",
  albumCaption2: "Nụ cười em là lý do khiến ngày hôm đó rực rỡ.",
  albumCaption3: "Mình nắm tay nhau qua từng con đường nhỏ.",
  albumCaption4: "Bình yên là khi có nhau trong từng khuôn hình.",
  albumCaption5: "Một ánh nhìn, một lời hứa, một đời thương.",
  albumCaption6: "Ngày hôm đó, thời gian như chậm lại.",
  albumCaption7: "Cảm ơn vì đã đến và ở lại bên nhau.",
  albumCaption8: "Những khoảnh khắc giản dị nhưng thật đáng nhớ.",
  albumCaption9: "Hạnh phúc của mình được viết bằng nụ cười.",
  albumCaption10: "Tình yêu là nhà, và mình là của nhau."
};
