window.WEDDING_TEXT = {
  coupleNames: "Khắc Tín - Yến Nhi",
  monogram: "T&N",
  weddingDate: "03.05.2026",
  // Dung cho countdown (ISO). Vi du: "2026-05-03T17:00:00+07:00"
  countdownTarget: "2026-05-03T17:00:00+07:00",
  inviteMessage: "Trân trọng kính mời quý khách tới dự bữa tiệc mừng lễ thành hôn của hai chúng tôi",
  coupleScript: "Khắc Tín<br>Yến Nhi",
  eventTime: "VÀO LÚC 17 GIỜ | CHỦ NHẬT",
  eventDateText: "NGÀY 03 THÁNG 05 NĂM 2026",
  eventDateLunar: "(TỨC NGÀY 17 THÁNG 03 NĂM BÍNH NGỌ)",
  brideFamily: "Ông Trần Ngọc Triệu<br>Bà Phạm Thị Bích Luận",
  groomFamily: "Ông Hồ Ngọc Cẩn<br>Bà Trần Thị Ngọc Linh",
  venueName: "Nhà Hàng Bá Hùng",
  venueAddress: "Số 58 đường Nguyễn Chí Thanh, Phước Nguyễn, Bà Rịa, Hồ Chí Minh",
  mapLink: "https://maps.app.goo.gl/yDk8pDZEdzDnJLib8",
  timelineDate: "03 . 05 . 2026",
  giftTitle: "Hộp mừng cưới",
  giftSubtitle: "Cảm ơn tình cảm của mọi người đã dành cho chúng mình!",
  guestbookTitle: "Sổ lưu bút",
  footerTitle: "Thank you",
  footerMessage: "Cảm ơn bạn đã dành tình cảm cho chúng mình!<br>Sự hiện diện của bạn chính là món quà ý nghĩa nhất.",
  albumCaption1: "Khoảnh khắc đầu tiên khi mình nhìn về nhau.",
  albumCaption2: "Nụ cười em là lý do khiến ngày hôm đó rực rỡ.",
  albumCaption3: "Mình nắm tay nhau qua từng con đường nhỏ.",
  albumCaption4: "Bình yên là khi có nhau trong từng khuôn hình.",
  albumCaption5: "Một ánh nhìn, một lời hứa, một đời thương.",
  albumCaption6: "Ngày hôm đó, thời gian như chậm lại.",
  albumCaption7: "Cảm ơn vì đã đến và ở lại bên nhau.",
  albumCaption8: "Những khoảnh khắc giản dị nhưng thật đáng nhớ.",
  albumCaption9: "Hạnh phúc của mình được viết bằng nụ cười.",
  albumCaption10: "Tình yêu là nhà, và mình là của nhau."
};
